export const devices = [
  {
    id: 1,
    name: "MacBook Air M2",
    category: "Laptop",
    price: 550,
    location: "AIT Campus",
    rating: 4.9,
    emoji: "💻",
  },
  {
    id: 2,
    name: "Sony A6400",
    category: "Camera",
    price: 420,
    location: "Bangkok",
    rating: 4.8,
    emoji: "📷",
  },
  {
    id: 3,
    name: "iPad Air",
    category: "Tablet",
    price: 300,
    location: "Pathum Thani",
    rating: 4.7,
    emoji: "📱",
  },
  {
    id: 4,
    name: "Nintendo Switch OLED",
    category: "Gaming",
    price: 250,
    location: "Bangkok",
    rating: 5,
    emoji: "🎮",
  },
  {
    id: 5,
    name: "Epson Projector",
    category: "Projector",
    price: 350,
    location: "AIT Campus",
    rating: 4.6,
    emoji: "📽️",
  },
  {
    id: 6,
    name: "DJI Mini Drone",
    category: "Creator Gear",
    price: 650,
    location: "Bangkok",
    rating: 4.9,
    emoji: "🚁",
  },
];